# coding: utf-8

"""
    Acqualify API Documentation

    The Acqualify API provides services to mortgage brokers and realtors to help applicants qualify for loans.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@creditsaint.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.applicants_api import ApplicantsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestApplicantsApi(unittest.TestCase):
    """ApplicantsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.applicants_api.ApplicantsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_lookup_applicant(self):
        """Test case for lookup_applicant

        Returns public information about a loan applicant  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
