# coding: utf-8

"""
    Acqualify API Documentation

    The Acqualify API provides services to mortgage brokers and realtors to help applicants qualify for loans.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@creditsaint.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]
    

setup(
    name=NAME,
    version=VERSION,
    description="Acqualify API Documentation",
    author_email="info@creditsaint.com",
    url="",
    keywords=["Swagger", "Acqualify API Documentation"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    The Acqualify API provides services to mortgage brokers and realtors to help applicants qualify for loans.  # noqa: E501
    """
)
