# coding: utf-8

# flake8: noqa
"""
    Acqualify API Documentation

    The Acqualify API provides services to mortgage brokers and realtors to help applicants qualify for loans.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@creditsaint.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
